package com.cdyne.ws.weatherws;

/**
 * This class was automatically generated by the data modeler tool.
 * $HASH(bff3a8045454c2d793aa7f76c5343ceb)
 */
public class WeatherReturn extends java.lang.Object implements java.io.Serializable {

    static final long serialVersionUID = 1L;
    
    @org.kie.api.definition.type.Position(value = 3)
    private java.lang.String city;
    
    @org.kie.api.definition.type.Position(value = 6)
    private java.lang.String description;
    
    @org.kie.api.definition.type.Position(value = 10)
    private java.lang.String pressure;
    
    @org.kie.api.definition.type.Position(value = 8)
    private java.lang.String relativeHumidity;
    
    @org.kie.api.definition.type.Position(value = 13)
    private java.lang.String remarks;
    
    @org.kie.api.definition.type.Position(value = 1)
    private java.lang.String responseText;
    
    @org.kie.api.definition.type.Position(value = 2)
    private java.lang.String state;
    
    @org.kie.api.definition.type.Position(value = 0)
    private java.lang.Boolean success;
    
    @org.kie.api.definition.type.Position(value = 7)
    private java.lang.String temperature;
    
    @org.kie.api.definition.type.Position(value = 11)
    private java.lang.String visibility;
    
    @org.kie.api.definition.type.Position(value = 5)
    private java.lang.Short weatherID;
    
    @org.kie.api.definition.type.Position(value = 4)
    private java.lang.String weatherStationCity;
    
    @org.kie.api.definition.type.Position(value = 9)
    private java.lang.String wind;
    
    @org.kie.api.definition.type.Position(value = 12)
    private java.lang.String windChill;

    public WeatherReturn() {
    }

    public WeatherReturn(java.lang.Boolean success, java.lang.String responseText, java.lang.String state, java.lang.String city, java.lang.String weatherStationCity, java.lang.Short weatherID, java.lang.String description, java.lang.String temperature, java.lang.String relativeHumidity, java.lang.String wind, java.lang.String pressure, java.lang.String visibility, java.lang.String windChill, java.lang.String remarks) {
        this.success = success;
        this.responseText = responseText;
        this.state = state;
        this.city = city;
        this.weatherStationCity = weatherStationCity;
        this.weatherID = weatherID;
        this.description = description;
        this.temperature = temperature;
        this.relativeHumidity = relativeHumidity;
        this.wind = wind;
        this.pressure = pressure;
        this.visibility = visibility;
        this.windChill = windChill;
        this.remarks = remarks;
    }


    
    public java.lang.String getCity() {
        return this.city;
    }

    public void setCity(java.lang.String city) {
        this.city = city;
    }
    
    public java.lang.String getDescription() {
        return this.description;
    }

    public void setDescription(java.lang.String description) {
        this.description = description;
    }
    
    public java.lang.String getPressure() {
        return this.pressure;
    }

    public void setPressure(java.lang.String pressure) {
        this.pressure = pressure;
    }
    
    public java.lang.String getRelativeHumidity() {
        return this.relativeHumidity;
    }

    public void setRelativeHumidity(java.lang.String relativeHumidity) {
        this.relativeHumidity = relativeHumidity;
    }
    
    public java.lang.String getRemarks() {
        return this.remarks;
    }

    public void setRemarks(java.lang.String remarks) {
        this.remarks = remarks;
    }
    
    public java.lang.String getResponseText() {
        return this.responseText;
    }

    public void setResponseText(java.lang.String responseText) {
        this.responseText = responseText;
    }
    
    public java.lang.String getState() {
        return this.state;
    }

    public void setState(java.lang.String state) {
        this.state = state;
    }
    
    public java.lang.Boolean getSuccess() {
        return this.success;
    }

    public void setSuccess(java.lang.Boolean success) {
        this.success = success;
    }
    
    public java.lang.String getTemperature() {
        return this.temperature;
    }

    public void setTemperature(java.lang.String temperature) {
        this.temperature = temperature;
    }
    
    public java.lang.String getVisibility() {
        return this.visibility;
    }

    public void setVisibility(java.lang.String visibility) {
        this.visibility = visibility;
    }
    
    public java.lang.Short getWeatherID() {
        return this.weatherID;
    }

    public void setWeatherID(java.lang.Short weatherID) {
        this.weatherID = weatherID;
    }
    
    public java.lang.String getWeatherStationCity() {
        return this.weatherStationCity;
    }

    public void setWeatherStationCity(java.lang.String weatherStationCity) {
        this.weatherStationCity = weatherStationCity;
    }
    
    public java.lang.String getWind() {
        return this.wind;
    }

    public void setWind(java.lang.String wind) {
        this.wind = wind;
    }
    
    public java.lang.String getWindChill() {
        return this.windChill;
    }

    public void setWindChill(java.lang.String windChill) {
        this.windChill = windChill;
    }
}