import com.miraca.eboss.demo.CaseMaster;
import com.miraca.eboss.demo.ChargeLine;
import org.jbpm.workflow.instance.WorkflowProcessInstance;

rule "88305 professional"
ruleflow-group "testtest"

dialect "mvel"

when
    cm : CaseMaster()
    item: ChargeLine(cpt == "88305", chargeType == "Professional" ) from cm.chargeLine
then
    insert (item);
    kcontext.getKnowledgeRuntime().getAgenda().getAgendaGroup( "Set Professional 88305" ).setFocus();
    System.out.println ("matched on 88305 and Professional. Total # of QTY: " + item.getTicketNumber() );
end

rule "Price for Professional 88305"

agenda-group "Set Professional 88305"
dialect "mvel"
lock-on-active true
when
   cm : CaseMaster()
   item : ChargeLine ()
   not String() from item.ticketNumber
then
    modify (item) {ticketNumber = cm.getCaseSource().getTicketNumber(), 
                           price = 100, totalPrice = item.getQty() * 100 };
   // modify(cm) {found = "yes"};
   // kcontext.getKnowledgeRuntime().getAgenda().getAgendaGroup( "Set Price Flag" ).setFocus();
    System.out.println ("Professional 88305 - Total Price Updated to this " + item.getTotalPrice() );
end
/*
rule "set flag"

agenda-group "Set Price Flag"
dialect "java"
lock-on-active true
when
   $proces : WorkflowProcessInstance()
then
         $proces.setVariable("validCount", (Integer) $proces.getVariable("validCount") + new Integer(1));    
          update($proces); 
          retract($proces);
          System.out.println ("updated valid count to: " + $proces.getVariable("validCount"));
end*/
