import com.miraca.eboss.demo.CaseMaster;
import com.miraca.eboss.demo.ChargeLine;

rule "88305 professional"
ruleflow-group "testtest"

dialect "mvel"

when
    cm : CaseMaster()
    item: ChargeLine(cpt == "88305", chargeType == "Professional" ) from cm.chargeLine
then
    modify (item) {setPrice(100.00), setTotalPrice(item.getQty() * 100) };
    System.out.println ("matched on 88305 and Professional. Total QTY: " + item.getQty());
end



rule "Check for anything"
ruleflow-group "testtest"

dialect "mvel"

when
then
    System.out.println ("Test test");
end