import com.miraca.eboss.demo.CaseMaster;
import com.miraca.eboss.demo.ChargeLine;

rule "88305 professional"
ruleflow-group "testtest"

dialect "mvel"

when
    cm : CaseMaster()
    item: ChargeLine(cpt == "88305", chargeType == "Professional" ) from cm.chargeLine
then
    modify (item) {price = 100.00, totalPrice = item.getQty() * 100.00}
    System.out.println ("matched on 88305 and Professional. Total Price: " + item.getTotalPrice());
end

rule "88305 Technical"
ruleflow-group "testtest"

dialect "mvel"

when
    cm : CaseMaster()
    item: ChargeLine(cpt == "88305", chargeType == "Technical" ) from cm.chargeLine
then
    modify (item) {price = 75.00, totalPrice = item.getQty() * 75.00 }
    System.out.println ("matched on 88305 and Technical. Total Price: " + item.getTotalPrice());
end

rule "88342 Professional"
ruleflow-group "testtest"

dialect "mvel"

when
    cm : CaseMaster()
    item: ChargeLine(cpt == "88342", chargeType == "Professional" ) from cm.chargeLine
then
    modify (item) {price = 150.00, totalPrice = item.getQty() * 150.00 }
    System.out.println ("matched on 88342 and Professional. Total Price: " + item.getTotalPrice());
end

rule "Check for anything"
ruleflow-group "testtest"

dialect "mvel"

when
then
    System.out.println ("Test test");
end