package com.miraca.eboss.demo;

/**
 * This class was automatically generated by the data modeler tool.
 * $HASH(6604e4607756fe143ca07f667aa6898e)
 */
public class CaseMaster extends java.lang.Object implements java.io.Serializable {

    static final long serialVersionUID = 1L;
    
    @org.kie.api.definition.type.Position(value = 2)
    private com.miraca.eboss.demo.Demographic caseDemographic;
    
    @org.kie.api.definition.type.Position(value = 1)
    private com.miraca.eboss.demo.CaseSource caseSource;
    
    @org.kie.api.definition.type.Position(value = 0)
    private com.miraca.eboss.demo.WeatherInfo weatherInfo;

    public CaseMaster() {
    }

    public CaseMaster(com.miraca.eboss.demo.WeatherInfo weatherInfo, com.miraca.eboss.demo.CaseSource caseSource, com.miraca.eboss.demo.Demographic caseDemographic) {
        this.weatherInfo = weatherInfo;
        this.caseSource = caseSource;
        this.caseDemographic = caseDemographic;
    }


    
    public com.miraca.eboss.demo.Demographic getCaseDemographic() {
        return this.caseDemographic;
    }

    public void setCaseDemographic(com.miraca.eboss.demo.Demographic caseDemographic) {
        this.caseDemographic = caseDemographic;
    }
    
    public com.miraca.eboss.demo.CaseSource getCaseSource() {
        return this.caseSource;
    }

    public void setCaseSource(com.miraca.eboss.demo.CaseSource caseSource) {
        this.caseSource = caseSource;
    }
    
    public com.miraca.eboss.demo.WeatherInfo getWeatherInfo() {
        return this.weatherInfo;
    }

    public void setWeatherInfo(com.miraca.eboss.demo.WeatherInfo weatherInfo) {
        this.weatherInfo = weatherInfo;
    }
}