package com.miraca.eboss.demo;

/**
 * This class was automatically generated by the data modeler tool.
 * $HASH(534a9c8a680a799130cfb7efb50bfa92)
 */
@org.kie.api.definition.type.Label(value = "City Weather By ZIP")
public class CityWeatherByZIP  implements java.io.Serializable {

    static final long serialVersionUID = 1L;
    
    @org.kie.api.definition.type.Position(value = 1)
    private java.lang.String city;
    
    @org.kie.api.definition.type.Position(value = 0)
    private java.lang.String state;
    
    @org.kie.api.definition.type.Position(value = 2)
    private java.lang.String temperature;

    public CityWeatherByZIP() {
    }

    public CityWeatherByZIP(java.lang.String state, java.lang.String city, java.lang.String temperature) {
        this.state = state;
        this.city = city;
        this.temperature = temperature;
    }


    
    public java.lang.String getCity() {
        return this.city;
    }

    public void setCity(java.lang.String city) {
        this.city = city;
    }
    
    public java.lang.String getState() {
        return this.state;
    }

    public void setState(java.lang.String state) {
        this.state = state;
    }
    
    public java.lang.String getTemperature() {
        return this.temperature;
    }

    public void setTemperature(java.lang.String temperature) {
        this.temperature = temperature;
    }
}