package com.miraca.eboss.demo;

/**
 * This class was automatically generated by the data modeler tool.
 * $HASH(2822866ee298362de179c41e5ef477cf)
 */
public class ValidCounter extends java.lang.Object implements java.io.Serializable {

    static final long serialVersionUID = 1L;
    
    @org.kie.api.definition.type.Position(value = 0)
    private java.lang.Integer counter;
    
    @org.kie.api.definition.type.Position(value = 1)
    private java.lang.Integer maxLineSize;

    public ValidCounter() {
    }

    public ValidCounter(java.lang.Integer counter, java.lang.Integer maxLineSize) {
        this.counter = counter;
        this.maxLineSize = maxLineSize;
    }


    
    public java.lang.Integer getCounter() {
        return this.counter;
    }

    public void setCounter(java.lang.Integer counter) {
        this.counter = counter;
    }
    
    public java.lang.Integer getMaxLineSize() {
        return this.maxLineSize;
    }

    public void setMaxLineSize(java.lang.Integer maxLineSize) {
        this.maxLineSize = maxLineSize;
    }
}